name: lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cli/**"
      - "libs/**"
      - "apps/**"
      - "services/**"
  pull_request:
    paths:
      - "cli/**"
      - "libs/**"
      - "apps/**"
      - "services/**"

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
